### ISSUE TITLE
Add FPS?

### ISSUE THREAD

**Issue by Thundros** [weiserhei/threejs-experiments#1]
@weiserhei : I had come across your site about a week ago & was wondering if you could update all your FPS demos? I would like to try them out.

Thanks!

**Comment by weiserhei** [comment]
Im in the process of refreshing all the projects to a modern build system using current librarys, starting with the easy ones :sweat_smile: 

Somewhere from threejs r70 they changed the way they handle matrix calculations (or something related to that) whereafter ammo.js and my character controller (which is based on https://github.com/insominx/WebFPS) broke. I can assure you Im also interested in upgrading these demos but this is more of a rewrite than just an update.
